### PR TITLE
new discover page

### PR DESCRIPTION
**Pull request by getneil**
TODOS:
- [x] remove tea icon in top bar
- [x] spotlight card
- [x] ai carousel-ish cards

https://www.loom.com/share/e52b751646f544eb8f5b386ca9bef239?from_recorder=1&focus_title=1

### CODE REVIEW

**Comment by getneil** [comment]
@tsmitty11 need to replace the `lorem ipsum` part.

**Comment by tsmitty11** [comment]
@getneil here's some copy. @mxcl to approve/tweak.

Explore the realm of local AI. This is your platform to tinker with high-profile AI tools like AutoGPT and Stable Diffusion Web UI, right from your local system. Jumpstart your AI projects while keeping your data safe and secure, with the freedom to fine-tune as you wish.

**Comment by tsmitty11** [comment]
Also sorry @getneil I didn't mean for logo to be removed from top bar yet. I left it out as is up in the air right now, but defer to this week's discussions around PKGX transition.

**Comment by getneil** [comment]
> Also sorry @getneil I didn't mean for logo to be removed from top bar yet. I left it out as is up in the air right now, but defer to this week's discussions around PKGX transition.

ok, brought back the tea logo.

**Pull request merged**
