### PR TITLE
Portuguese (Brazil) translation

### PR DESCRIPTION
**Pull request by ricardoprins**
Hi!

This is the translation to Portuguese (Brazil). I hope this helps! Keep it up, I've loved this pkg manager!

### CODE REVIEW

**Comment by getneil** [comment]
@ricardoprins thank you for contributing. The pr has issues with liniting, you can just run `$ xc prettier` should help fix it. 

Also is there a 2-letter code for this language/country?

**Comment by ricardoprins** [comment]
There is; however, Brazilian Portuguese is a little different from Portugal Portuguese, and it is usually the norm to use pt-br to differentiate both.

I'll run the linter here.

**Comment by getneil** [comment]
@ricardoprins thanks for enlightening us.

**Comment by getneil** [comment]
@ricardoprins you need to execute in the root `$ xc prettier` then stage and commit the changes.

**Comment by ricardoprins** [comment]
I'll do it later today :) gonna take my kid to have some fun first haha

**Comment by getneil** [comment]
@ricardoprins thank you merging this now.

**Pull request merged**
