### PR TITLE
use big image with center element focus

### PR DESCRIPTION
**Pull request by getneil**
Screenshot 2023-05-08 at 2 09 13 PM

Screenshot 2023-05-08 at 2 09 07 PM

### CODE REVIEW

**Comment by getneil** [comment]
DO NOT MERGE UNTIL ALL IMAGES ARE UPDATED

**Comment by getneil** [comment]
@tsmitty11 we are probably not doing this anymore right?

**Comment by tsmitty11** [comment]
@getneil no, as it's been remedied via other means; and we have a discover page re-design coming down the pipeline anyways.

**Comment by getneil** [comment]
not needed anymore

**Pull request closed without merging**
